# fly.toml file generated for rentagpt2 on 2023-04-05T11:41:13+02:00

app = "rentagpt2"
kill_timeout = 0
primary_region = "mad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  LOG_LEVEL = "debug"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
