# fly.toml file generated for rentagpt on 2023-04-04T12:00:23+02:00

app = "rentagpt"
primary_region = "mad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  LOG_LEVEL = "debug"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
